#!/usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'pyprobe==1.0','console_scripts','pyprobe'
__requires__ = 'pyprobe==1.0'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('pyprobe==1.0', 'console_scripts', 'pyprobe')()
    )
